### PR TITLE
docs: spell check and trailing whitespace

### PR DESCRIPTION
**Pull request by gvwilson**
1.  Check spelling in `.md` files using `aspell`.
2.  Remove end-of-line whitespace.

### CODE REVIEW

**Comment by vitostamatti** [comment]
wow! thank you for taking the time to collaborate! i really appreciate it! i you feel like adding more examples or you have any ideas to you'd like to work on, feel free to propose them

**Comment by gvwilson** [comment]
Glad I could help - I'm working on adding a couple of examples to https://third-bit.com/sdxpy/ that use Py-DES, so it seemed the least I could do. I don't suppose you have a few more examples I could study, particularly something that demonstrates nonlinearity in network congestion or server congestion? thanks - @gvwilson (gvwilson@third-bit.com if you'd rather switch to email)

**Comment by vitostamatti** [comment]
Keep in mind that this package is completely in dev mode and is not pretended to be used as an stable library. I'm still thinking about the best api and even considering using async instead of greenlet in near future. I've mostly used DES for logistics in my professional work. I'd like to have more "real" examples but i have to come up with an stable api before that.  Maybe is a good discussion  to open.

**Comment by gvwilson** [comment]
Thanks Vito - I think that working backward from a handful of examples would be a great way to figure out what the API should be. (I also think you should stick with greenlet, but that's a separate discussion :-) ) If you ever want to kick ideas around, please drop me an email - always happy to chat.

**Pull request merged**
